version: '3'
services:
  node:
    build: .
    container_name: node
    volumes:
      - ..:/workout-app:cached
    # command: /bin/sh -c "cd workout-app && npm run dev"
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"